### ISSUE TITLE
Compiling grey-cuckoo on Guest VM (OSX 10.13)

### ISSUE THREAD

**Issue by PwnU** [phdphuc/mac-a-mal-cuckoo#4]
Grey-cuckoo builds but no executable is created.
Without it every time I kextload mac-a-mal.kext the VM reboots.

Any help ?

**Comment by phdphuc** [comment]
There are a kext and a MachO binary would be compiled as output. Please notice mac-a-mal.kext was tested successfully on macOS <= 10.12. I will try on 10.13 soon and let you know. Btw, it would be great if you create this separate ticket on [mac-a-mal](https://github.com/phdphuc/mac-a-mal).
