### ISSUE TITLE
Unable to load mac-a-mal.kext because of missed signature

### ISSUE THREAD

**Issue by zentavr** [phdphuc/mac-a-mal-cuckoo#7]
Hi,

I was able to compile the kext file, but seems like but cannot be loaded because of the missed signature. The guest (VurtualBox) is MacOS 10.12 and the error is:
```
    Ians-iMac:mam ian$ sudo kextutil /Library/Extensions/mac-a-mal.kext
    Diagnostics for /Library/Extensions/mac-a-mal.kext:
    Code Signing Failure: not code signed
    Untrusted kexts are not allowed
    ERROR: invalid signature for mac-a-mal, will not load
```

I wonder if there is any workaround to do the trick?

**Comment by phdphuc** [comment]
You can either [sign the KEXT](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/KernelExtensions/KernelExtensions.html), or disable the KEXT verification from the SIP in the recovery mode with this command: `csrutil enable --without kext`.
